from transformers import GPT2Tokenizer, GPT2LMHeadModel
import numpy as np
import random
import scipy.stats as st

def primitive_detect_watermark(input_str, prompt_len, seed, gamma):
    # works reliably with hard watermark. With soft watermark, probably produces lots of false positives
    tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
    inputs = tokenizer(input_str, return_tensors="pt")
    tokens = inputs['input_ids'][0]

    flag = True
    for i in range(prompt_len - 1, len(tokens) - 1):
        random.seed(seed + tokens[i].item())

        for _ in range(tokens[i + 1] + 1):
            is_red = gamma > random.random()
        
        if is_red:
            print("not watermarked text")
            return False # determined not to be watermarked

    prob = (1/2) ** (len(tokens) - prompt_len)
    print(f"probability {prob} that this text is generated, watermarked text")
    return flag # it's watermarked

def fancy_detect_watermark(input_str, prompt_len, seed, gamma):
    tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
    inputs = tokenizer(input_str, return_tensors="pt")
    tokens = inputs['input_ids'][0]

    green_count = 0
    total_count = len(tokens) - prompt_len

    for i in range(prompt_len - 1, len(tokens) - 1):
        random.seed(seed + tokens[i].item())
    
        for _ in range(tokens[i + 1] + 1):
            is_red = gamma > random.random()

        if not is_red:
            green_count += 1

    z = (green_count - (gamma * total_count))/ np.sqrt(total_count * gamma * (1-gamma))
    prob = st.norm.cdf(z)
    print(f"probability that text is generated by watermarked model: {prob}")
    return prob


def main():
    hard = "Recently, scientists have discovered that cosmic microwave mirrors reflect primary radiation and begin to ripples in red photons running away, but nothing"
    soft = "Recently, scientists have discovered a further evolution in how mammals use rubber pellets boating. Man can manage a test dummy using the"
    none = "The naive approach to solving these 100 linear systems would be to solve each system separately using Gaussian elimination and back substitution, which would require a total of 100 times the computation required to solve a single system."
    prompt_len = 5
    # primitive_detect_watermark(soft, prompt_len, seed = 1729, gamma = 0.5)
    # primitive_detect_watermark(soft, prompt_len, seed = 1729, gamma = 0.5) # might say it's not watermarked -- that's expected behavior
    # primitive_detect_watermark(none, prompt_len, seed = 1729, gamma = 0.5)

    fancy_detect_watermark(none, prompt_len, seed = 1729, gamma = 0.5)
    # fancy_detect_watermark(soft, prompt_len, seed = 1729, gamma = 0.5)
    # fancy_detect_watermark(none, prompt_len, seed = 1729, gamma = 0.5)
    
    

if __name__ == "__main__":
    main()
